version: '2'
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  haml-lint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-10-0
exclude_patterns:
- bin/**/*
- coverage/**/*
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
