require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config.ru'
    - 'bin/**/*'
    - 'config/{environments,initializers}/*'
    - 'config/{application,boot,environment,puma,spring}.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  - spec/**/*.rb
  - db/seeds.rb

RSpec:
  Enabled: false

RSpec/BeEql:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true

# Don't worry about documentation for now.
# In particular, this fails for things like
# controller files, which seems unnecessary.
Style/Documentation:
  Enabled: false
