require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config.ru'
    - 'bin/**/*'
    - 'config/{environments,initializers}/*'
    - 'config/{application,boot,environment,puma,spring}.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  - spec/**/*.rb
  - db/seeds.rb

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - spec/{system,views}/**/*.rb

# Don't worry about documentation for now.
# In particular, this fails for things like
# controller files, which seems unnecessary.
Style/Documentation:
  Enabled: false
